version: "3.7"
services:
  frontend:
    build: .
    stdin_open: true
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      - NODE_ENV=development
